# Generated by Django 3.0.4 on 2020-03-12 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shiftswap', '0003_auto_20200312_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
    ]
