# Generated by Django 3.0.4 on 2020-03-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftswap', '0004_jobcard_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='description',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
