# Generated by Django 3.0.4 on 2020-03-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftswap', '0005_auto_20200312_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_contractor',
            field=models.BooleanField(default=False),
        ),
    ]
