# Generated by Django 3.0.2 on 2020-03-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftswap', '0006_user_is_contractor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcard',
            old_name='end_date',
            new_name='end_time',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='start_date',
        ),
        migrations.AddField(
            model_name='jobcard',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='start_time',
            field=models.TimeField(default=None),
        ),
    ]
