# Generated by Django 3.0.4 on 2020-03-20 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shiftswap', '0007_auto_20200320_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='applied',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.PROTECT, related_name='jobcards_applied', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
