# Generated by Django 3.0.4 on 2020-03-30 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shiftswap', '0007_auto_20200320_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_company', to=settings.AUTH_USER_MODEL),
        ),
    ]
