# Generated by Django 3.0.4 on 2020-03-30 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftswap', '0008_auto_20200330_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='applied',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
