# Generated by Django 3.0.4 on 2020-03-20 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shiftswap', '0008_jobcard_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcard',
            name='applied',
        ),
    ]
