# Generated by Django 3.0.4 on 2020-03-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftswap', '0009_jobcard_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='review',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
