# Generated by Django 3.0.4 on 2020-03-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftswap', '0012_jobcard_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='applied',
            field=models.ManyToManyField(blank=True, null=True, related_name='_jobcard_applied_+', to='shiftswap.JobCard'),
        ),
    ]
