# Generated by Django 3.0.4 on 2020-03-30 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shiftswap', '0013_auto_20200330_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcard',
            name='applied',
        ),
        migrations.CreateModel(
            name='AppliedJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shiftswap.JobCard')),
            ],
        ),
    ]
