# Generated by Django 3.0.4 on 2020-03-30 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shiftswap', '0014_auto_20200330_1950'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppliedJobs',
            new_name='AppliedJob',
        ),
    ]
