# Generated by Django 3.0.4 on 2020-03-30 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftswap', '0016_auto_20200330_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='applied',
            field=models.ManyToManyField(related_name='applied', to=settings.AUTH_USER_MODEL),
        ),
    ]
